/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.components;

import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

public class ActivityStatsResponseDto {

    @JsonProperty("monthlySent")
    private double monthlySent;

    @JsonProperty("weeklySent")
    private double weeklySent;

    @JsonCreator
    public ActivityStatsResponseDto(
            @JsonProperty("monthlySent") double monthlySent,
            @JsonProperty("weeklySent") double weeklySent) {
        Utils.checkNotNull(monthlySent, "monthlySent");
        Utils.checkNotNull(weeklySent, "weeklySent");
        this.monthlySent = monthlySent;
        this.weeklySent = weeklySent;
    }

    @JsonIgnore
    public double monthlySent() {
        return monthlySent;
    }

    @JsonIgnore
    public double weeklySent() {
        return weeklySent;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ActivityStatsResponseDto withMonthlySent(double monthlySent) {
        Utils.checkNotNull(monthlySent, "monthlySent");
        this.monthlySent = monthlySent;
        return this;
    }

    public ActivityStatsResponseDto withWeeklySent(double weeklySent) {
        Utils.checkNotNull(weeklySent, "weeklySent");
        this.weeklySent = weeklySent;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ActivityStatsResponseDto other = (ActivityStatsResponseDto) o;
        return 
            java.util.Objects.deepEquals(this.monthlySent, other.monthlySent) &&
            java.util.Objects.deepEquals(this.weeklySent, other.weeklySent);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            monthlySent,
            weeklySent);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ActivityStatsResponseDto.class,
                "monthlySent", monthlySent,
                "weeklySent", weeklySent);
    }
    
    public final static class Builder {
 
        private Double monthlySent;
 
        private Double weeklySent;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder monthlySent(double monthlySent) {
            Utils.checkNotNull(monthlySent, "monthlySent");
            this.monthlySent = monthlySent;
            return this;
        }

        public Builder weeklySent(double weeklySent) {
            Utils.checkNotNull(weeklySent, "weeklySent");
            this.weeklySent = weeklySent;
            return this;
        }
        
        public ActivityStatsResponseDto build() {
            return new ActivityStatsResponseDto(
                monthlySent,
                weeklySent);
        }
    }
}

