/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.components;

import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;

public class GetSubscriberPreferencesResponseDto {

    /**
     * The preferences of the subscriber regarding the related workflow
     */
    @JsonProperty("preference")
    private Preference preference;

    /**
     * The workflow information and if it is critical or not
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("template")
    private Optional<? extends TemplateResponse> template;

    @JsonCreator
    public GetSubscriberPreferencesResponseDto(
            @JsonProperty("preference") Preference preference,
            @JsonProperty("template") Optional<? extends TemplateResponse> template) {
        Utils.checkNotNull(preference, "preference");
        Utils.checkNotNull(template, "template");
        this.preference = preference;
        this.template = template;
    }
    
    public GetSubscriberPreferencesResponseDto(
            Preference preference) {
        this(preference, Optional.empty());
    }

    /**
     * The preferences of the subscriber regarding the related workflow
     */
    @JsonIgnore
    public Preference preference() {
        return preference;
    }

    /**
     * The workflow information and if it is critical or not
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<TemplateResponse> template() {
        return (Optional<TemplateResponse>) template;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The preferences of the subscriber regarding the related workflow
     */
    public GetSubscriberPreferencesResponseDto withPreference(Preference preference) {
        Utils.checkNotNull(preference, "preference");
        this.preference = preference;
        return this;
    }

    /**
     * The workflow information and if it is critical or not
     */
    public GetSubscriberPreferencesResponseDto withTemplate(TemplateResponse template) {
        Utils.checkNotNull(template, "template");
        this.template = Optional.ofNullable(template);
        return this;
    }

    /**
     * The workflow information and if it is critical or not
     */
    public GetSubscriberPreferencesResponseDto withTemplate(Optional<? extends TemplateResponse> template) {
        Utils.checkNotNull(template, "template");
        this.template = template;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetSubscriberPreferencesResponseDto other = (GetSubscriberPreferencesResponseDto) o;
        return 
            java.util.Objects.deepEquals(this.preference, other.preference) &&
            java.util.Objects.deepEquals(this.template, other.template);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            preference,
            template);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetSubscriberPreferencesResponseDto.class,
                "preference", preference,
                "template", template);
    }
    
    public final static class Builder {
 
        private Preference preference;
 
        private Optional<? extends TemplateResponse> template = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The preferences of the subscriber regarding the related workflow
         */
        public Builder preference(Preference preference) {
            Utils.checkNotNull(preference, "preference");
            this.preference = preference;
            return this;
        }

        /**
         * The workflow information and if it is critical or not
         */
        public Builder template(TemplateResponse template) {
            Utils.checkNotNull(template, "template");
            this.template = Optional.ofNullable(template);
            return this;
        }

        /**
         * The workflow information and if it is critical or not
         */
        public Builder template(Optional<? extends TemplateResponse> template) {
            Utils.checkNotNull(template, "template");
            this.template = template;
            return this;
        }
        
        public GetSubscriberPreferencesResponseDto build() {
            return new GetSubscriberPreferencesResponseDto(
                preference,
                template);
        }
    }
}

