/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.components;

import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;

public class TriggerEventRequestDto {

    /**
     * It is used to display the Avatar of the provided actor's subscriber id or actor object.
     *     If a new actor object is provided, we will create a new subscriber in our system
     *     
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("actor")
    private Optional<? extends Actor> actor;

    /**
     * The trigger identifier of the workflow you wish to send. This identifier can be found on the workflow page.
     */
    @JsonProperty("name")
    private String name;

    /**
     * This could be used to override provider specific configurations
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("overrides")
    private Optional<? extends TriggerEventRequestDtoOverrides> overrides;

    /**
     * The payload object is used to pass additional custom information that could be used to render the workflow, or perform routing rules based on it. 
     *       This data will also be available when fetching the notifications feed from the API to display certain parts of the UI.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payload")
    private Optional<? extends TriggerEventRequestDtoPayload> payload;

    /**
     * It is used to specify a tenant context during trigger event.
     *     Existing tenants will be updated with the provided details.
     *     
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tenant")
    private Optional<? extends Tenant> tenant;

    /**
     * The recipients list of people who will receive the notification.
     */
    @JsonProperty("to")
    private java.util.List<To> to;

    /**
     * A unique identifier for this transaction, we will generated a UUID if not provided.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transactionId")
    private Optional<? extends String> transactionId;

    @JsonCreator
    public TriggerEventRequestDto(
            @JsonProperty("actor") Optional<? extends Actor> actor,
            @JsonProperty("name") String name,
            @JsonProperty("overrides") Optional<? extends TriggerEventRequestDtoOverrides> overrides,
            @JsonProperty("payload") Optional<? extends TriggerEventRequestDtoPayload> payload,
            @JsonProperty("tenant") Optional<? extends Tenant> tenant,
            @JsonProperty("to") java.util.List<To> to,
            @JsonProperty("transactionId") Optional<? extends String> transactionId) {
        Utils.checkNotNull(actor, "actor");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(overrides, "overrides");
        Utils.checkNotNull(payload, "payload");
        Utils.checkNotNull(tenant, "tenant");
        Utils.checkNotNull(to, "to");
        Utils.checkNotNull(transactionId, "transactionId");
        this.actor = actor;
        this.name = name;
        this.overrides = overrides;
        this.payload = payload;
        this.tenant = tenant;
        this.to = to;
        this.transactionId = transactionId;
    }
    
    public TriggerEventRequestDto(
            String name,
            java.util.List<To> to) {
        this(Optional.empty(), name, Optional.empty(), Optional.empty(), Optional.empty(), to, Optional.empty());
    }

    /**
     * It is used to display the Avatar of the provided actor's subscriber id or actor object.
     *     If a new actor object is provided, we will create a new subscriber in our system
     *     
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Actor> actor() {
        return (Optional<Actor>) actor;
    }

    /**
     * The trigger identifier of the workflow you wish to send. This identifier can be found on the workflow page.
     */
    @JsonIgnore
    public String name() {
        return name;
    }

    /**
     * This could be used to override provider specific configurations
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<TriggerEventRequestDtoOverrides> overrides() {
        return (Optional<TriggerEventRequestDtoOverrides>) overrides;
    }

    /**
     * The payload object is used to pass additional custom information that could be used to render the workflow, or perform routing rules based on it. 
     *       This data will also be available when fetching the notifications feed from the API to display certain parts of the UI.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<TriggerEventRequestDtoPayload> payload() {
        return (Optional<TriggerEventRequestDtoPayload>) payload;
    }

    /**
     * It is used to specify a tenant context during trigger event.
     *     Existing tenants will be updated with the provided details.
     *     
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Tenant> tenant() {
        return (Optional<Tenant>) tenant;
    }

    /**
     * The recipients list of people who will receive the notification.
     */
    @JsonIgnore
    public java.util.List<To> to() {
        return to;
    }

    /**
     * A unique identifier for this transaction, we will generated a UUID if not provided.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> transactionId() {
        return (Optional<String>) transactionId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * It is used to display the Avatar of the provided actor's subscriber id or actor object.
     *     If a new actor object is provided, we will create a new subscriber in our system
     *     
     */
    public TriggerEventRequestDto withActor(Actor actor) {
        Utils.checkNotNull(actor, "actor");
        this.actor = Optional.ofNullable(actor);
        return this;
    }

    /**
     * It is used to display the Avatar of the provided actor's subscriber id or actor object.
     *     If a new actor object is provided, we will create a new subscriber in our system
     *     
     */
    public TriggerEventRequestDto withActor(Optional<? extends Actor> actor) {
        Utils.checkNotNull(actor, "actor");
        this.actor = actor;
        return this;
    }

    /**
     * The trigger identifier of the workflow you wish to send. This identifier can be found on the workflow page.
     */
    public TriggerEventRequestDto withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * This could be used to override provider specific configurations
     */
    public TriggerEventRequestDto withOverrides(TriggerEventRequestDtoOverrides overrides) {
        Utils.checkNotNull(overrides, "overrides");
        this.overrides = Optional.ofNullable(overrides);
        return this;
    }

    /**
     * This could be used to override provider specific configurations
     */
    public TriggerEventRequestDto withOverrides(Optional<? extends TriggerEventRequestDtoOverrides> overrides) {
        Utils.checkNotNull(overrides, "overrides");
        this.overrides = overrides;
        return this;
    }

    /**
     * The payload object is used to pass additional custom information that could be used to render the workflow, or perform routing rules based on it. 
     *       This data will also be available when fetching the notifications feed from the API to display certain parts of the UI.
     */
    public TriggerEventRequestDto withPayload(TriggerEventRequestDtoPayload payload) {
        Utils.checkNotNull(payload, "payload");
        this.payload = Optional.ofNullable(payload);
        return this;
    }

    /**
     * The payload object is used to pass additional custom information that could be used to render the workflow, or perform routing rules based on it. 
     *       This data will also be available when fetching the notifications feed from the API to display certain parts of the UI.
     */
    public TriggerEventRequestDto withPayload(Optional<? extends TriggerEventRequestDtoPayload> payload) {
        Utils.checkNotNull(payload, "payload");
        this.payload = payload;
        return this;
    }

    /**
     * It is used to specify a tenant context during trigger event.
     *     Existing tenants will be updated with the provided details.
     *     
     */
    public TriggerEventRequestDto withTenant(Tenant tenant) {
        Utils.checkNotNull(tenant, "tenant");
        this.tenant = Optional.ofNullable(tenant);
        return this;
    }

    /**
     * It is used to specify a tenant context during trigger event.
     *     Existing tenants will be updated with the provided details.
     *     
     */
    public TriggerEventRequestDto withTenant(Optional<? extends Tenant> tenant) {
        Utils.checkNotNull(tenant, "tenant");
        this.tenant = tenant;
        return this;
    }

    /**
     * The recipients list of people who will receive the notification.
     */
    public TriggerEventRequestDto withTo(java.util.List<To> to) {
        Utils.checkNotNull(to, "to");
        this.to = to;
        return this;
    }

    /**
     * A unique identifier for this transaction, we will generated a UUID if not provided.
     */
    public TriggerEventRequestDto withTransactionId(String transactionId) {
        Utils.checkNotNull(transactionId, "transactionId");
        this.transactionId = Optional.ofNullable(transactionId);
        return this;
    }

    /**
     * A unique identifier for this transaction, we will generated a UUID if not provided.
     */
    public TriggerEventRequestDto withTransactionId(Optional<? extends String> transactionId) {
        Utils.checkNotNull(transactionId, "transactionId");
        this.transactionId = transactionId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TriggerEventRequestDto other = (TriggerEventRequestDto) o;
        return 
            java.util.Objects.deepEquals(this.actor, other.actor) &&
            java.util.Objects.deepEquals(this.name, other.name) &&
            java.util.Objects.deepEquals(this.overrides, other.overrides) &&
            java.util.Objects.deepEquals(this.payload, other.payload) &&
            java.util.Objects.deepEquals(this.tenant, other.tenant) &&
            java.util.Objects.deepEquals(this.to, other.to) &&
            java.util.Objects.deepEquals(this.transactionId, other.transactionId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            actor,
            name,
            overrides,
            payload,
            tenant,
            to,
            transactionId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TriggerEventRequestDto.class,
                "actor", actor,
                "name", name,
                "overrides", overrides,
                "payload", payload,
                "tenant", tenant,
                "to", to,
                "transactionId", transactionId);
    }
    
    public final static class Builder {
 
        private Optional<? extends Actor> actor = Optional.empty();
 
        private String name;
 
        private Optional<? extends TriggerEventRequestDtoOverrides> overrides = Optional.empty();
 
        private Optional<? extends TriggerEventRequestDtoPayload> payload = Optional.empty();
 
        private Optional<? extends Tenant> tenant = Optional.empty();
 
        private java.util.List<To> to;
 
        private Optional<? extends String> transactionId = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * It is used to display the Avatar of the provided actor's subscriber id or actor object.
         *     If a new actor object is provided, we will create a new subscriber in our system
         *     
         */
        public Builder actor(Actor actor) {
            Utils.checkNotNull(actor, "actor");
            this.actor = Optional.ofNullable(actor);
            return this;
        }

        /**
         * It is used to display the Avatar of the provided actor's subscriber id or actor object.
         *     If a new actor object is provided, we will create a new subscriber in our system
         *     
         */
        public Builder actor(Optional<? extends Actor> actor) {
            Utils.checkNotNull(actor, "actor");
            this.actor = actor;
            return this;
        }

        /**
         * The trigger identifier of the workflow you wish to send. This identifier can be found on the workflow page.
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }

        /**
         * This could be used to override provider specific configurations
         */
        public Builder overrides(TriggerEventRequestDtoOverrides overrides) {
            Utils.checkNotNull(overrides, "overrides");
            this.overrides = Optional.ofNullable(overrides);
            return this;
        }

        /**
         * This could be used to override provider specific configurations
         */
        public Builder overrides(Optional<? extends TriggerEventRequestDtoOverrides> overrides) {
            Utils.checkNotNull(overrides, "overrides");
            this.overrides = overrides;
            return this;
        }

        /**
         * The payload object is used to pass additional custom information that could be used to render the workflow, or perform routing rules based on it. 
         *       This data will also be available when fetching the notifications feed from the API to display certain parts of the UI.
         */
        public Builder payload(TriggerEventRequestDtoPayload payload) {
            Utils.checkNotNull(payload, "payload");
            this.payload = Optional.ofNullable(payload);
            return this;
        }

        /**
         * The payload object is used to pass additional custom information that could be used to render the workflow, or perform routing rules based on it. 
         *       This data will also be available when fetching the notifications feed from the API to display certain parts of the UI.
         */
        public Builder payload(Optional<? extends TriggerEventRequestDtoPayload> payload) {
            Utils.checkNotNull(payload, "payload");
            this.payload = payload;
            return this;
        }

        /**
         * It is used to specify a tenant context during trigger event.
         *     Existing tenants will be updated with the provided details.
         *     
         */
        public Builder tenant(Tenant tenant) {
            Utils.checkNotNull(tenant, "tenant");
            this.tenant = Optional.ofNullable(tenant);
            return this;
        }

        /**
         * It is used to specify a tenant context during trigger event.
         *     Existing tenants will be updated with the provided details.
         *     
         */
        public Builder tenant(Optional<? extends Tenant> tenant) {
            Utils.checkNotNull(tenant, "tenant");
            this.tenant = tenant;
            return this;
        }

        /**
         * The recipients list of people who will receive the notification.
         */
        public Builder to(java.util.List<To> to) {
            Utils.checkNotNull(to, "to");
            this.to = to;
            return this;
        }

        /**
         * A unique identifier for this transaction, we will generated a UUID if not provided.
         */
        public Builder transactionId(String transactionId) {
            Utils.checkNotNull(transactionId, "transactionId");
            this.transactionId = Optional.ofNullable(transactionId);
            return this;
        }

        /**
         * A unique identifier for this transaction, we will generated a UUID if not provided.
         */
        public Builder transactionId(Optional<? extends String> transactionId) {
            Utils.checkNotNull(transactionId, "transactionId");
            this.transactionId = transactionId;
            return this;
        }
        
        public TriggerEventRequestDto build() {
            return new TriggerEventRequestDto(
                actor,
                name,
                overrides,
                payload,
                tenant,
                to,
                transactionId);
        }
    }
}

