/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.operations;

import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.http.HttpResponse;
import java.util.Optional;

public class EventsControllerTriggerBulkResponse implements co.novu.co.novu.sdk.utils.Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Created
     */
    private Optional<? extends java.util.List<co.novu.co.novu.sdk.models.components.TriggerEventResponseDto>> triggerEventResponseDtos;

    @JsonCreator
    public EventsControllerTriggerBulkResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends java.util.List<co.novu.co.novu.sdk.models.components.TriggerEventResponseDto>> triggerEventResponseDtos) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(triggerEventResponseDtos, "triggerEventResponseDtos");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.triggerEventResponseDtos = triggerEventResponseDtos;
    }
    
    public EventsControllerTriggerBulkResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Created
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<java.util.List<co.novu.co.novu.sdk.models.components.TriggerEventResponseDto>> triggerEventResponseDtos() {
        return (Optional<java.util.List<co.novu.co.novu.sdk.models.components.TriggerEventResponseDto>>) triggerEventResponseDtos;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public EventsControllerTriggerBulkResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public EventsControllerTriggerBulkResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public EventsControllerTriggerBulkResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Created
     */
    public EventsControllerTriggerBulkResponse withTriggerEventResponseDtos(java.util.List<co.novu.co.novu.sdk.models.components.TriggerEventResponseDto> triggerEventResponseDtos) {
        Utils.checkNotNull(triggerEventResponseDtos, "triggerEventResponseDtos");
        this.triggerEventResponseDtos = Optional.ofNullable(triggerEventResponseDtos);
        return this;
    }

    /**
     * Created
     */
    public EventsControllerTriggerBulkResponse withTriggerEventResponseDtos(Optional<? extends java.util.List<co.novu.co.novu.sdk.models.components.TriggerEventResponseDto>> triggerEventResponseDtos) {
        Utils.checkNotNull(triggerEventResponseDtos, "triggerEventResponseDtos");
        this.triggerEventResponseDtos = triggerEventResponseDtos;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EventsControllerTriggerBulkResponse other = (EventsControllerTriggerBulkResponse) o;
        return 
            java.util.Objects.deepEquals(this.contentType, other.contentType) &&
            java.util.Objects.deepEquals(this.statusCode, other.statusCode) &&
            java.util.Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            java.util.Objects.deepEquals(this.triggerEventResponseDtos, other.triggerEventResponseDtos);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            triggerEventResponseDtos);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EventsControllerTriggerBulkResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "triggerEventResponseDtos", triggerEventResponseDtos);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends java.util.List<co.novu.co.novu.sdk.models.components.TriggerEventResponseDto>> triggerEventResponseDtos = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Created
         */
        public Builder triggerEventResponseDtos(java.util.List<co.novu.co.novu.sdk.models.components.TriggerEventResponseDto> triggerEventResponseDtos) {
            Utils.checkNotNull(triggerEventResponseDtos, "triggerEventResponseDtos");
            this.triggerEventResponseDtos = Optional.ofNullable(triggerEventResponseDtos);
            return this;
        }

        /**
         * Created
         */
        public Builder triggerEventResponseDtos(Optional<? extends java.util.List<co.novu.co.novu.sdk.models.components.TriggerEventResponseDto>> triggerEventResponseDtos) {
            Utils.checkNotNull(triggerEventResponseDtos, "triggerEventResponseDtos");
            this.triggerEventResponseDtos = triggerEventResponseDtos;
            return this;
        }
        
        public EventsControllerTriggerBulkResponse build() {
            return new EventsControllerTriggerBulkResponse(
                contentType,
                statusCode,
                rawResponse,
                triggerEventResponseDtos);
        }
    }
}

