/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.operations;

import co.novu.co.novu.sdk.models.errors.SDKError;
import co.novu.co.novu.sdk.utils.LazySingletonValue;
import co.novu.co.novu.sdk.utils.Options.Builder;
import co.novu.co.novu.sdk.utils.Options;
import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;


public class LayoutsControllerUpdateLayoutRequestBuilder {

    private String layoutId;
    private co.novu.co.novu.sdk.models.components.UpdateLayoutRequestDto updateLayoutRequestDto;
    private Optional<co.novu.co.novu.sdk.utils.RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallLayoutsControllerUpdateLayout sdk;

    public LayoutsControllerUpdateLayoutRequestBuilder(SDKMethodInterfaces.MethodCallLayoutsControllerUpdateLayout sdk) {
        this.sdk = sdk;
    }

    public LayoutsControllerUpdateLayoutRequestBuilder layoutId(String layoutId) {
        Utils.checkNotNull(layoutId, "layoutId");
        this.layoutId = layoutId;
        return this;
    }

    public LayoutsControllerUpdateLayoutRequestBuilder updateLayoutRequestDto(co.novu.co.novu.sdk.models.components.UpdateLayoutRequestDto updateLayoutRequestDto) {
        Utils.checkNotNull(updateLayoutRequestDto, "updateLayoutRequestDto");
        this.updateLayoutRequestDto = updateLayoutRequestDto;
        return this;
    }
                
    public LayoutsControllerUpdateLayoutRequestBuilder retryConfig(co.novu.co.novu.sdk.utils.RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public LayoutsControllerUpdateLayoutRequestBuilder retryConfig(Optional<co.novu.co.novu.sdk.utils.RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public LayoutsControllerUpdateLayoutResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.update(
            layoutId,
            updateLayoutRequestDto,
            options);
    }
}
