/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.operations;

import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.http.HttpResponse;
import java.util.Optional;

public class OrganizationControllerGetSelfOrganizationDataResponse implements co.novu.co.novu.sdk.utils.Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * Ok
     */
    private Optional<? extends co.novu.co.novu.sdk.models.components.OrganizationResponseDto> organizationResponseDto;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    @JsonCreator
    public OrganizationControllerGetSelfOrganizationDataResponse(
            String contentType,
            Optional<? extends co.novu.co.novu.sdk.models.components.OrganizationResponseDto> organizationResponseDto,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(organizationResponseDto, "organizationResponseDto");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.contentType = contentType;
        this.organizationResponseDto = organizationResponseDto;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }
    
    public OrganizationControllerGetSelfOrganizationDataResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, Optional.empty(), statusCode, rawResponse);
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * Ok
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<co.novu.co.novu.sdk.models.components.OrganizationResponseDto> organizationResponseDto() {
        return (Optional<co.novu.co.novu.sdk.models.components.OrganizationResponseDto>) organizationResponseDto;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public OrganizationControllerGetSelfOrganizationDataResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * Ok
     */
    public OrganizationControllerGetSelfOrganizationDataResponse withOrganizationResponseDto(co.novu.co.novu.sdk.models.components.OrganizationResponseDto organizationResponseDto) {
        Utils.checkNotNull(organizationResponseDto, "organizationResponseDto");
        this.organizationResponseDto = Optional.ofNullable(organizationResponseDto);
        return this;
    }

    /**
     * Ok
     */
    public OrganizationControllerGetSelfOrganizationDataResponse withOrganizationResponseDto(Optional<? extends co.novu.co.novu.sdk.models.components.OrganizationResponseDto> organizationResponseDto) {
        Utils.checkNotNull(organizationResponseDto, "organizationResponseDto");
        this.organizationResponseDto = organizationResponseDto;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public OrganizationControllerGetSelfOrganizationDataResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public OrganizationControllerGetSelfOrganizationDataResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrganizationControllerGetSelfOrganizationDataResponse other = (OrganizationControllerGetSelfOrganizationDataResponse) o;
        return 
            java.util.Objects.deepEquals(this.contentType, other.contentType) &&
            java.util.Objects.deepEquals(this.organizationResponseDto, other.organizationResponseDto) &&
            java.util.Objects.deepEquals(this.statusCode, other.statusCode) &&
            java.util.Objects.deepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            contentType,
            organizationResponseDto,
            statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(OrganizationControllerGetSelfOrganizationDataResponse.class,
                "contentType", contentType,
                "organizationResponseDto", organizationResponseDto,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Optional<? extends co.novu.co.novu.sdk.models.components.OrganizationResponseDto> organizationResponseDto = Optional.empty();
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * Ok
         */
        public Builder organizationResponseDto(co.novu.co.novu.sdk.models.components.OrganizationResponseDto organizationResponseDto) {
            Utils.checkNotNull(organizationResponseDto, "organizationResponseDto");
            this.organizationResponseDto = Optional.ofNullable(organizationResponseDto);
            return this;
        }

        /**
         * Ok
         */
        public Builder organizationResponseDto(Optional<? extends co.novu.co.novu.sdk.models.components.OrganizationResponseDto> organizationResponseDto) {
            Utils.checkNotNull(organizationResponseDto, "organizationResponseDto");
            this.organizationResponseDto = organizationResponseDto;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }
        
        public OrganizationControllerGetSelfOrganizationDataResponse build() {
            return new OrganizationControllerGetSelfOrganizationDataResponse(
                contentType,
                organizationResponseDto,
                statusCode,
                rawResponse);
        }
    }
}

