/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.operations;

import co.novu.co.novu.sdk.utils.SpeakeasyMetadata;
import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

public class OrganizationControllerRemoveRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=memberId")
    private String memberId;

    @JsonCreator
    public OrganizationControllerRemoveRequest(
            String memberId) {
        Utils.checkNotNull(memberId, "memberId");
        this.memberId = memberId;
    }

    @JsonIgnore
    public String memberId() {
        return memberId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public OrganizationControllerRemoveRequest withMemberId(String memberId) {
        Utils.checkNotNull(memberId, "memberId");
        this.memberId = memberId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrganizationControllerRemoveRequest other = (OrganizationControllerRemoveRequest) o;
        return 
            java.util.Objects.deepEquals(this.memberId, other.memberId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            memberId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(OrganizationControllerRemoveRequest.class,
                "memberId", memberId);
    }
    
    public final static class Builder {
 
        private String memberId;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder memberId(String memberId) {
            Utils.checkNotNull(memberId, "memberId");
            this.memberId = memberId;
            return this;
        }
        
        public OrganizationControllerRemoveRequest build() {
            return new OrganizationControllerRemoveRequest(
                memberId);
        }
    }
}

