/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.operations;

import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.http.HttpResponse;
import java.util.Optional;

public class SubscribersControllerUpdateSubscriberPreferenceResponse implements co.novu.co.novu.sdk.utils.Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Ok
     */
    private Optional<? extends co.novu.co.novu.sdk.models.components.UpdateSubscriberPreferenceResponseDto> updateSubscriberPreferenceResponseDto;

    @JsonCreator
    public SubscribersControllerUpdateSubscriberPreferenceResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends co.novu.co.novu.sdk.models.components.UpdateSubscriberPreferenceResponseDto> updateSubscriberPreferenceResponseDto) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(updateSubscriberPreferenceResponseDto, "updateSubscriberPreferenceResponseDto");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.updateSubscriberPreferenceResponseDto = updateSubscriberPreferenceResponseDto;
    }
    
    public SubscribersControllerUpdateSubscriberPreferenceResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Ok
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<co.novu.co.novu.sdk.models.components.UpdateSubscriberPreferenceResponseDto> updateSubscriberPreferenceResponseDto() {
        return (Optional<co.novu.co.novu.sdk.models.components.UpdateSubscriberPreferenceResponseDto>) updateSubscriberPreferenceResponseDto;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public SubscribersControllerUpdateSubscriberPreferenceResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public SubscribersControllerUpdateSubscriberPreferenceResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public SubscribersControllerUpdateSubscriberPreferenceResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Ok
     */
    public SubscribersControllerUpdateSubscriberPreferenceResponse withUpdateSubscriberPreferenceResponseDto(co.novu.co.novu.sdk.models.components.UpdateSubscriberPreferenceResponseDto updateSubscriberPreferenceResponseDto) {
        Utils.checkNotNull(updateSubscriberPreferenceResponseDto, "updateSubscriberPreferenceResponseDto");
        this.updateSubscriberPreferenceResponseDto = Optional.ofNullable(updateSubscriberPreferenceResponseDto);
        return this;
    }

    /**
     * Ok
     */
    public SubscribersControllerUpdateSubscriberPreferenceResponse withUpdateSubscriberPreferenceResponseDto(Optional<? extends co.novu.co.novu.sdk.models.components.UpdateSubscriberPreferenceResponseDto> updateSubscriberPreferenceResponseDto) {
        Utils.checkNotNull(updateSubscriberPreferenceResponseDto, "updateSubscriberPreferenceResponseDto");
        this.updateSubscriberPreferenceResponseDto = updateSubscriberPreferenceResponseDto;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscribersControllerUpdateSubscriberPreferenceResponse other = (SubscribersControllerUpdateSubscriberPreferenceResponse) o;
        return 
            java.util.Objects.deepEquals(this.contentType, other.contentType) &&
            java.util.Objects.deepEquals(this.statusCode, other.statusCode) &&
            java.util.Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            java.util.Objects.deepEquals(this.updateSubscriberPreferenceResponseDto, other.updateSubscriberPreferenceResponseDto);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            updateSubscriberPreferenceResponseDto);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscribersControllerUpdateSubscriberPreferenceResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "updateSubscriberPreferenceResponseDto", updateSubscriberPreferenceResponseDto);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends co.novu.co.novu.sdk.models.components.UpdateSubscriberPreferenceResponseDto> updateSubscriberPreferenceResponseDto = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Ok
         */
        public Builder updateSubscriberPreferenceResponseDto(co.novu.co.novu.sdk.models.components.UpdateSubscriberPreferenceResponseDto updateSubscriberPreferenceResponseDto) {
            Utils.checkNotNull(updateSubscriberPreferenceResponseDto, "updateSubscriberPreferenceResponseDto");
            this.updateSubscriberPreferenceResponseDto = Optional.ofNullable(updateSubscriberPreferenceResponseDto);
            return this;
        }

        /**
         * Ok
         */
        public Builder updateSubscriberPreferenceResponseDto(Optional<? extends co.novu.co.novu.sdk.models.components.UpdateSubscriberPreferenceResponseDto> updateSubscriberPreferenceResponseDto) {
            Utils.checkNotNull(updateSubscriberPreferenceResponseDto, "updateSubscriberPreferenceResponseDto");
            this.updateSubscriberPreferenceResponseDto = updateSubscriberPreferenceResponseDto;
            return this;
        }
        
        public SubscribersControllerUpdateSubscriberPreferenceResponse build() {
            return new SubscribersControllerUpdateSubscriberPreferenceResponse(
                contentType,
                statusCode,
                rawResponse,
                updateSubscriberPreferenceResponseDto);
        }
    }
}

