/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.operations;

import co.novu.co.novu.sdk.utils.SpeakeasyMetadata;
import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

public class SubscribersControllerMarkAllUnreadAsReadRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=subscriberId")
    private String subscriberId;

    @SpeakeasyMetadata("request:mediaType=application/json")
    private co.novu.co.novu.sdk.models.components.MarkAllMessageAsRequestDto markAllMessageAsRequestDto;

    @JsonCreator
    public SubscribersControllerMarkAllUnreadAsReadRequest(
            String subscriberId,
            co.novu.co.novu.sdk.models.components.MarkAllMessageAsRequestDto markAllMessageAsRequestDto) {
        Utils.checkNotNull(subscriberId, "subscriberId");
        Utils.checkNotNull(markAllMessageAsRequestDto, "markAllMessageAsRequestDto");
        this.subscriberId = subscriberId;
        this.markAllMessageAsRequestDto = markAllMessageAsRequestDto;
    }

    @JsonIgnore
    public String subscriberId() {
        return subscriberId;
    }

    @JsonIgnore
    public co.novu.co.novu.sdk.models.components.MarkAllMessageAsRequestDto markAllMessageAsRequestDto() {
        return markAllMessageAsRequestDto;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public SubscribersControllerMarkAllUnreadAsReadRequest withSubscriberId(String subscriberId) {
        Utils.checkNotNull(subscriberId, "subscriberId");
        this.subscriberId = subscriberId;
        return this;
    }

    public SubscribersControllerMarkAllUnreadAsReadRequest withMarkAllMessageAsRequestDto(co.novu.co.novu.sdk.models.components.MarkAllMessageAsRequestDto markAllMessageAsRequestDto) {
        Utils.checkNotNull(markAllMessageAsRequestDto, "markAllMessageAsRequestDto");
        this.markAllMessageAsRequestDto = markAllMessageAsRequestDto;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscribersControllerMarkAllUnreadAsReadRequest other = (SubscribersControllerMarkAllUnreadAsReadRequest) o;
        return 
            java.util.Objects.deepEquals(this.subscriberId, other.subscriberId) &&
            java.util.Objects.deepEquals(this.markAllMessageAsRequestDto, other.markAllMessageAsRequestDto);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            subscriberId,
            markAllMessageAsRequestDto);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscribersControllerMarkAllUnreadAsReadRequest.class,
                "subscriberId", subscriberId,
                "markAllMessageAsRequestDto", markAllMessageAsRequestDto);
    }
    
    public final static class Builder {
 
        private String subscriberId;
 
        private co.novu.co.novu.sdk.models.components.MarkAllMessageAsRequestDto markAllMessageAsRequestDto;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder subscriberId(String subscriberId) {
            Utils.checkNotNull(subscriberId, "subscriberId");
            this.subscriberId = subscriberId;
            return this;
        }

        public Builder markAllMessageAsRequestDto(co.novu.co.novu.sdk.models.components.MarkAllMessageAsRequestDto markAllMessageAsRequestDto) {
            Utils.checkNotNull(markAllMessageAsRequestDto, "markAllMessageAsRequestDto");
            this.markAllMessageAsRequestDto = markAllMessageAsRequestDto;
            return this;
        }
        
        public SubscribersControllerMarkAllUnreadAsReadRequest build() {
            return new SubscribersControllerMarkAllUnreadAsReadRequest(
                subscriberId,
                markAllMessageAsRequestDto);
        }
    }
}

