/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.operations;

import co.novu.co.novu.sdk.utils.SpeakeasyMetadata;
import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

public class SubscribersControllerGetUnseenCountRequest {

    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=seen")
    private boolean seen;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=subscriberId")
    private String subscriberId;

    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    private double limit;

    @JsonCreator
    public SubscribersControllerGetUnseenCountRequest(
            boolean seen,
            String subscriberId,
            double limit) {
        Utils.checkNotNull(seen, "seen");
        Utils.checkNotNull(subscriberId, "subscriberId");
        Utils.checkNotNull(limit, "limit");
        this.seen = seen;
        this.subscriberId = subscriberId;
        this.limit = limit;
    }

    @JsonIgnore
    public boolean seen() {
        return seen;
    }

    @JsonIgnore
    public String subscriberId() {
        return subscriberId;
    }

    @JsonIgnore
    public double limit() {
        return limit;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public SubscribersControllerGetUnseenCountRequest withSeen(boolean seen) {
        Utils.checkNotNull(seen, "seen");
        this.seen = seen;
        return this;
    }

    public SubscribersControllerGetUnseenCountRequest withSubscriberId(String subscriberId) {
        Utils.checkNotNull(subscriberId, "subscriberId");
        this.subscriberId = subscriberId;
        return this;
    }

    public SubscribersControllerGetUnseenCountRequest withLimit(double limit) {
        Utils.checkNotNull(limit, "limit");
        this.limit = limit;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscribersControllerGetUnseenCountRequest other = (SubscribersControllerGetUnseenCountRequest) o;
        return 
            java.util.Objects.deepEquals(this.seen, other.seen) &&
            java.util.Objects.deepEquals(this.subscriberId, other.subscriberId) &&
            java.util.Objects.deepEquals(this.limit, other.limit);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            seen,
            subscriberId,
            limit);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscribersControllerGetUnseenCountRequest.class,
                "seen", seen,
                "subscriberId", subscriberId,
                "limit", limit);
    }
    
    public final static class Builder {
 
        private Boolean seen;
 
        private String subscriberId;
 
        private Double limit;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder seen(boolean seen) {
            Utils.checkNotNull(seen, "seen");
            this.seen = seen;
            return this;
        }

        public Builder subscriberId(String subscriberId) {
            Utils.checkNotNull(subscriberId, "subscriberId");
            this.subscriberId = subscriberId;
            return this;
        }

        public Builder limit(double limit) {
            Utils.checkNotNull(limit, "limit");
            this.limit = limit;
            return this;
        }
        
        public SubscribersControllerGetUnseenCountRequest build() {
            return new SubscribersControllerGetUnseenCountRequest(
                seen,
                subscriberId,
                limit);
        }
    }
}

