/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.operations;

import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.http.HttpResponse;
import java.util.Optional;

public class SubscribersControllerMarkMessagesAsResponse implements co.novu.co.novu.sdk.utils.Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    private Optional<? extends java.util.List<co.novu.co.novu.sdk.models.components.MessageEntity>> messageEntities;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    @JsonCreator
    public SubscribersControllerMarkMessagesAsResponse(
            String contentType,
            Optional<? extends java.util.List<co.novu.co.novu.sdk.models.components.MessageEntity>> messageEntities,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(messageEntities, "messageEntities");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.contentType = contentType;
        this.messageEntities = messageEntities;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }
    
    public SubscribersControllerMarkMessagesAsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, Optional.empty(), statusCode, rawResponse);
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<java.util.List<co.novu.co.novu.sdk.models.components.MessageEntity>> messageEntities() {
        return (Optional<java.util.List<co.novu.co.novu.sdk.models.components.MessageEntity>>) messageEntities;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public SubscribersControllerMarkMessagesAsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    public SubscribersControllerMarkMessagesAsResponse withMessageEntities(java.util.List<co.novu.co.novu.sdk.models.components.MessageEntity> messageEntities) {
        Utils.checkNotNull(messageEntities, "messageEntities");
        this.messageEntities = Optional.ofNullable(messageEntities);
        return this;
    }

    public SubscribersControllerMarkMessagesAsResponse withMessageEntities(Optional<? extends java.util.List<co.novu.co.novu.sdk.models.components.MessageEntity>> messageEntities) {
        Utils.checkNotNull(messageEntities, "messageEntities");
        this.messageEntities = messageEntities;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public SubscribersControllerMarkMessagesAsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public SubscribersControllerMarkMessagesAsResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscribersControllerMarkMessagesAsResponse other = (SubscribersControllerMarkMessagesAsResponse) o;
        return 
            java.util.Objects.deepEquals(this.contentType, other.contentType) &&
            java.util.Objects.deepEquals(this.messageEntities, other.messageEntities) &&
            java.util.Objects.deepEquals(this.statusCode, other.statusCode) &&
            java.util.Objects.deepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            contentType,
            messageEntities,
            statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscribersControllerMarkMessagesAsResponse.class,
                "contentType", contentType,
                "messageEntities", messageEntities,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Optional<? extends java.util.List<co.novu.co.novu.sdk.models.components.MessageEntity>> messageEntities = Optional.empty();
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        public Builder messageEntities(java.util.List<co.novu.co.novu.sdk.models.components.MessageEntity> messageEntities) {
            Utils.checkNotNull(messageEntities, "messageEntities");
            this.messageEntities = Optional.ofNullable(messageEntities);
            return this;
        }

        public Builder messageEntities(Optional<? extends java.util.List<co.novu.co.novu.sdk.models.components.MessageEntity>> messageEntities) {
            Utils.checkNotNull(messageEntities, "messageEntities");
            this.messageEntities = messageEntities;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }
        
        public SubscribersControllerMarkMessagesAsResponse build() {
            return new SubscribersControllerMarkMessagesAsResponse(
                contentType,
                messageEntities,
                statusCode,
                rawResponse);
        }
    }
}

