/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.operations;

import co.novu.co.novu.sdk.utils.SpeakeasyMetadata;
import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

public class SubscribersControllerMarkMessagesAsRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=subscriberId")
    private String subscriberId;

    @SpeakeasyMetadata("request:mediaType=application/json")
    private co.novu.co.novu.sdk.models.components.MessageMarkAsRequestDto messageMarkAsRequestDto;

    @JsonCreator
    public SubscribersControllerMarkMessagesAsRequest(
            String subscriberId,
            co.novu.co.novu.sdk.models.components.MessageMarkAsRequestDto messageMarkAsRequestDto) {
        Utils.checkNotNull(subscriberId, "subscriberId");
        Utils.checkNotNull(messageMarkAsRequestDto, "messageMarkAsRequestDto");
        this.subscriberId = subscriberId;
        this.messageMarkAsRequestDto = messageMarkAsRequestDto;
    }

    @JsonIgnore
    public String subscriberId() {
        return subscriberId;
    }

    @JsonIgnore
    public co.novu.co.novu.sdk.models.components.MessageMarkAsRequestDto messageMarkAsRequestDto() {
        return messageMarkAsRequestDto;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public SubscribersControllerMarkMessagesAsRequest withSubscriberId(String subscriberId) {
        Utils.checkNotNull(subscriberId, "subscriberId");
        this.subscriberId = subscriberId;
        return this;
    }

    public SubscribersControllerMarkMessagesAsRequest withMessageMarkAsRequestDto(co.novu.co.novu.sdk.models.components.MessageMarkAsRequestDto messageMarkAsRequestDto) {
        Utils.checkNotNull(messageMarkAsRequestDto, "messageMarkAsRequestDto");
        this.messageMarkAsRequestDto = messageMarkAsRequestDto;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscribersControllerMarkMessagesAsRequest other = (SubscribersControllerMarkMessagesAsRequest) o;
        return 
            java.util.Objects.deepEquals(this.subscriberId, other.subscriberId) &&
            java.util.Objects.deepEquals(this.messageMarkAsRequestDto, other.messageMarkAsRequestDto);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            subscriberId,
            messageMarkAsRequestDto);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscribersControllerMarkMessagesAsRequest.class,
                "subscriberId", subscriberId,
                "messageMarkAsRequestDto", messageMarkAsRequestDto);
    }
    
    public final static class Builder {
 
        private String subscriberId;
 
        private co.novu.co.novu.sdk.models.components.MessageMarkAsRequestDto messageMarkAsRequestDto;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder subscriberId(String subscriberId) {
            Utils.checkNotNull(subscriberId, "subscriberId");
            this.subscriberId = subscriberId;
            return this;
        }

        public Builder messageMarkAsRequestDto(co.novu.co.novu.sdk.models.components.MessageMarkAsRequestDto messageMarkAsRequestDto) {
            Utils.checkNotNull(messageMarkAsRequestDto, "messageMarkAsRequestDto");
            this.messageMarkAsRequestDto = messageMarkAsRequestDto;
            return this;
        }
        
        public SubscribersControllerMarkMessagesAsRequest build() {
            return new SubscribersControllerMarkMessagesAsRequest(
                subscriberId,
                messageMarkAsRequestDto);
        }
    }
}

