/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package co.novu.co.novu.sdk.models.operations;

import co.novu.co.novu.sdk.models.errors.SDKError;
import co.novu.co.novu.sdk.utils.LazySingletonValue;
import co.novu.co.novu.sdk.utils.Options.Builder;
import co.novu.co.novu.sdk.utils.Options;
import co.novu.co.novu.sdk.utils.Utils;
import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;


public class TenantControllerUpdateTenantRequestBuilder {

    private String identifier;
    private co.novu.co.novu.sdk.models.components.UpdateTenantRequestDto updateTenantRequestDto;
    private Optional<co.novu.co.novu.sdk.utils.RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallTenantControllerUpdateTenant sdk;

    public TenantControllerUpdateTenantRequestBuilder(SDKMethodInterfaces.MethodCallTenantControllerUpdateTenant sdk) {
        this.sdk = sdk;
    }

    public TenantControllerUpdateTenantRequestBuilder identifier(String identifier) {
        Utils.checkNotNull(identifier, "identifier");
        this.identifier = identifier;
        return this;
    }

    public TenantControllerUpdateTenantRequestBuilder updateTenantRequestDto(co.novu.co.novu.sdk.models.components.UpdateTenantRequestDto updateTenantRequestDto) {
        Utils.checkNotNull(updateTenantRequestDto, "updateTenantRequestDto");
        this.updateTenantRequestDto = updateTenantRequestDto;
        return this;
    }
                
    public TenantControllerUpdateTenantRequestBuilder retryConfig(co.novu.co.novu.sdk.utils.RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public TenantControllerUpdateTenantRequestBuilder retryConfig(Optional<co.novu.co.novu.sdk.utils.RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public TenantControllerUpdateTenantResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.update(
            identifier,
            updateTenantRequestDto,
            options);
    }
}
